on: [push]

name: mipsel build

jobs:
  linux_arm7:
    name: Linux mipsel
    runs-on: ubuntu-latest
    steps:
      - name: install rust toolchain
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly
      - name: build
        run: |
          cargo build --release --target mipsel-unknown-linux-gnu
